env:
  global:
    - CC_TEST_REPORTER_ID=00d7c4b3b6dc5d82b6acec8a801381c5c2652c0326dbc3407c147799f0e7757f
    
before_script:
  - psql -c "CREATE DATABASE pgapp_test;" -U postgres

  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install:
 - gem update --system
 - gem install bundler

rvm:
 - 2.5.0

script:
 - bundle exec rspec spec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
  - postgresql
